spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.28:3300/bpm02?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 3edc4rfv
    dbType: mysql
  activemq:
    broker-url: tcp://127.0.0.1:61616
    in-memory: false
    packages:
      trust-all: true


logging:
  path: /logs/bpm/
  level:
    root: debug
    org.springframework.data.redis: info
server:
  context-path: /

## security:
##  ignored:  [/agilebpm-ui/** ,/css/**, /js/**,/images/**,/webjars/**,/**/favicon.ico]
## /swagger-*,/v2/api-docs*,   swagger 免登陆

ab:
  jwt:
    enabled: false
  security:
    auth-ingores: /login.*,/agilebpm-ui*,/index.html,/swagger-*,/v2/api-docs*,
  redis:
    host: 192.168.8.28
    password: 3edc4rfv
    use-redis-cache: false
  mail:
    mail-address: xxx@qq.com
    nick-name: BPM
    password: fywouffpohiibdee-i
    send-host: smtp.qq.com
    send-port: 465


## 上传配置 db 存数据库 ，具体请看 IUploader 实现类
uploader:
  default: db